IF OBJECT_ID('bronze.application_train', 'U') IS NOT NULL
	DROP TABLE bronze.application_train;
GO
CREATE TABLE bronze.application_train(
SK_ID_CURR INT,
TARGET INT,
NAME_CONTRACT_TYPE NVARCHAR(50),
CODE_GENDER NVARCHAR(50),
FLAG_OWN_CAR INT,
FLAG_OWN_REALTY INT, 
AMT_INCOME_TOTAL INT,
AMT_CREDIT INT,
AMT_ANNUITY INT,
AMT_GOODS_PRICE INT,
NAME_INCOME_TYPE NVARCHAR(50),
NAME_EDUCATION_TYPE NVARCHAR(50),
NAME_FAMILY_STATUS NVARCHAR(50),
NAME_HOUSING_TYPE NVARCHAR(50),
REGION_POPULATION_RELATIVE INT,	
AGE INT,
YEARS_EMPLOYED INT,
YEARS_REGISTERED INT,
OCCUPATION_TYPE NVARCHAR(50),
REGION_RATING_CLIENT INT,
REGION_RATING_CLIENT_W_CITY INT,
WEEKDAY_APPR_PROCESS_START NVARCHAR(50),
ORGANIZATION_TYPE NVARCHAR(50),
EXT_SOURCE INT,
DEF_60_SOCIAL_CIRCLE_PCT NVARCHAR(50),
AMT_REQ_CREDIT_BUREAU_YEAR INT
);

GO
IF OBJECT_ID('bronze.previous_application', 'U') IS NOT NULL
	DROP TABLE bronze.previous_application;
GO
CREATE TABLE bronze.previous_application(
SK_ID_PREV INT,
SK_ID_CURR INT,
NAME_CONTRACT_TYPE NVARCHAR(50),
AMT_ANNUITY INT,
AMT_APPLICATION INT,
AMT_CREDIT INT,
AMT_DOWN_PAYMENT INT,
AMT_GOODS_PRICE INT,
WEEKDAY_APPR_PROCESS_START NVARCHAR(50),
HOUR_APPR_PROCESS_START NVARCHAR(50),
FLAG_LAST_APPL_PER_CONTRACT NVARCHAR(50),
NFLAG_LAST_APPL_IN_DAY NVARCHAR(50),
RATE_DOWN_PAYMENT INT,
RATE_INTEREST_PRIMARY INT,
RATE_INTEREST_PRIVILEGED INT,
NAME_CASH_LOAN_PURPOSE NVARCHAR(50),
NAME_CONTRACT_STATUS NVARCHAR(50),
DAYS_DECISION NVARCHAR(50),
NAME_PAYMENT_TYPE NVARCHAR(50),
CODE_REJECT_REASON NVARCHAR(50),
NAME_TYPE_SUITE NVARCHAR(50),
NAME_CLIENT_TYPE NVARCHAR(50),
NAME_GOODS_CATEGORY NVARCHAR(50),
NAME_PORTFOLIO NVARCHAR(50),
NAME_PRODUCT_TYPE NVARCHAR(50),
CHANNEL_TYPE NVARCHAR(50),
SELLERPLACE_AREA NVARCHAR(50),
NAME_SELLER_INDUSTRY NVARCHAR(50),
CNT_PAYMENT NVARCHAR(50),
NAME_YIELD_GROUP NVARCHAR(50),
PRODUCT_COMBINATION NVARCHAR(50),
DAYS_FIRST_DRAWING NVARCHAR(50),
DAYS_FIRST_DUE NVARCHAR(50),
DAYS_LAST_DUE_1ST_VERSION NVARCHAR(50),
DAYS_LAST_DUE NVARCHAR(50),
DAYS_TERMINATION NVARCHAR(50),
NFLAG_INSURED_ON_APPROVAL NVARCHAR(50)
);
GO

IF OBJECT_ID('bronze.bureau', 'U') IS NOT NULL
	DROP TABLE bronze.bureau;
GO
CREATE TABLE bronze.bureau(
SK_ID_CURR INT,
SK_ID_BUREAU INT,
CREDIT_ACTIVE NVARCHAR(50),
CREDIT_CURRENCY NVARCHAR(50),
DAYS_CREDIT INT,
CREDIT_DAY_OVERDUE INT,
DAYS_CREDIT_ENDDATE INT,
DAYS_ENDDATE_FACT INT,
AMT_CREDIT_MAX_OVERDUE INT,
CNT_CREDIT_PROLONG INT,
AMT_CREDIT_SUM INT,
AMT_CREDIT_SUM_DEBT INT,
AMT_CREDIT_SUM_LIMIT INT,
AMT_CREDIT_SUM_OVERDUE INT,
CREDIT_TYPE NVARCHAR(50),
DAYS_CREDIT_UPDATE NVARCHAR(50),
AMT_ANNUITY INT
);
GO
IF OBJECT_ID('bronze.credit_card_balance', 'U') IS NOT NULL
	DROP TABLE bronze.credit_card_balance;
GO
CREATE TABLE bronze.credit_card_balance(
SK_ID_PREV INT,
SK_ID_CURR INT,
MONTHS_BALANCE INT,
AMT_BALANCE INT,
AMT_CREDIT_LIMIT_ACTUAL INT,
AMT_DRAWINGS_ATM_CURRENT INT,
AMT_DRAWINGS_CURRENT INT,
AMT_DRAWINGS_OTHER_CURRENT INT,
AMT_DRAWINGS_POS_CURRENT INT,
AMT_INST_MIN_REGULARITY INT,
AMT_PAYMENT_CURRENT INT,
AMT_PAYMENT_TOTAL_CURRENT INT,
AMT_RECEIVABLE_PRINCIPAL INT,
AMT_RECIVABLE INT,
AMT_TOTAL_RECEIVABLE INT,
CNT_DRAWINGS_ATM_CURRENT INT,
CNT_DRAWINGS_CURRENT INT,
CNT_DRAWINGS_OTHER_CURRENT INT,
CNT_DRAWINGS_POS_CURRENT INT,
CNT_INSTALMENT_MATURE_CUM INT,
NAME_CONTRACT_STATUS NVARCHAR(50),
SK_DPD INT,
SK_DPD_DEF INT
);
 GO
IF OBJECT_ID('bronze.installments_payments', 'U')
	DROP TABLE bronze.installments_payments;
GO
CREATE TABLE bronze.installments_payments(
SK_ID_PREV INT,
SK_ID_CURR INT,
NUM_INSTALMENT_VERSION INT,
NUM_INSTALMENT_NUMBER INT,
DAYS_INSTALMENT	INT,
DAYS_ENTRY_PAYMENT INT,
AMT_INSTALMENT INT,
AMT_PAYMENT INT
);
GO
IF OBJECT_ID('POS_CASH_balance','U')
	DROP TABLE POS_CASH_balance;
GO
CREATE TABLE POS_CASH_balance(
SK_ID_PREV INT,
SK_ID_CURR INT,
MONTHS_BALANCE INT,
CNT_INSTALMENT INT,
CNT_INSTALMENT_FUTURE INT,
NAME_CONTRACT_STATUS NVARCHAR(50),
SK_DPD INT,
SK_DPD_DEF INT
);
GO
IF OBJECT_ID('bureau_balance', 'U')
	DROP TABLE bureau_balance;
GO
CREATE TABLE bureau_balance(
SK_ID_BUREAU INT,
MONTHS_BALANCE INT,
STATUS NVARCHAR(50)
)
