

IF OBJECT_ID('bronze.application_train', 'U') IS NOT NULL
	DROP TABLE bronze.application_train;
GO
CREATE TABLE bronze.application_train(
SK_ID_CURR NVARCHAR(50),
TARGET INT,
NAME_CONTRACT_TYPE NVARCHAR(50),
CODE_GENDER NVARCHAR(50),
FLAG_OWN_CAR INT,
FLAG_OWN_REALTY INT, 
AMT_INCOME_TOTAL FLOAT,
AMT_CREDIT FLOAT,
AMT_ANNUITY FLOAT,
AMT_GOODS_PRICE FLOAT,
NAME_INCOME_TYPE NVARCHAR(50),
NAME_EDUCATION_TYPE NVARCHAR(50),
NAME_FAMILY_STATUS NVARCHAR(50),
NAME_HOUSING_TYPE NVARCHAR(50),
REGION_POPULATION_RELATIVE FLOAT,	
AGE INT,
YEARS_EMPLOYED INT,
YEARS_REGISTERED INT,
OCCUPATION_TYPE NVARCHAR(50),
REGION_RATING_CLIENT INT,
REGION_RATING_CLIENT_W_CITY INT,
WEEKDAY_APPR_PROCESS_START NVARCHAR(50),
ORGANIZATION_TYPE NVARCHAR(50),
EXT_SOURCE FLOAT,
DEF_60_SOCIAL_CIRCLE_PCT NVARCHAR(50),
AMT_REQ_CREDIT_BUREAU_YEAR INT
)


