/*
==================================================================================
Silver Data Definition Script
==================================================================================
Script Purpose:
    This script creates a second phase of the tables in the Silver Schema to accept only relevant columns across all datasets
==================================================================================

*/

IF OBJECT_ID('silver.application_train', 'U') IS NOT NULL
	DROP TABLE silver.application_train;
GO
CREATE TABLE silver.application_train(
SK_ID_CURR NVARCHAR(50),
TARGET NVARCHAR(50),
NAME_CONTRACT_TYPE NVARCHAR(50),
CODE_GENDER NVARCHAR(50),
FLAG_OWN_CAR NVARCHAR(50),
FLAG_OWN_REALTY NVARCHAR(50), 
AMT_INCOME_TOTAL NVARCHAR(50),
AMT_CREDIT NVARCHAR(50),
AMT_ANNUITY NVARCHAR(50),
AMT_GOODS_PRICE NVARCHAR(50),
NAME_INCOME_TYPE NVARCHAR(50),
NAME_EDUCATION_TYPE NVARCHAR(50),
NAME_FAMILY_STATUS NVARCHAR(50),
NAME_HOUSING_TYPE NVARCHAR(50),
REGION_POPULATION_RELATIVE NVARCHAR(50),	
AGE NVARCHAR(50),
YEARS_EMPLOYED NVARCHAR(50),
YEARS_REGISTERED NVARCHAR(50),
OCCUPATION_TYPE NVARCHAR(50),
REGION_RATING_CLIENT NVARCHAR(50),
REGION_RATING_CLIENT_W_CITY NVARCHAR(50),
WEEKDAY_APPR_PROCESS_START NVARCHAR(50),
ORGANIZATION_TYPE NVARCHAR(50),
EXT_SOURCE NVARCHAR(50),
DEF_60_SOCIAL_CIRCLE_PCT NVARCHAR(50),
AMT_REQ_CREDIT_BUREAU_YEAR NVARCHAR(50)
);

GO
IF OBJECT_ID('silver.previous_application', 'U') IS NOT NULL
	DROP TABLE silver.previous_application;
GO
CREATE TABLE silver.previous_application(
SK_ID_PREV NVARCHAR(MAX),
SK_ID_CURR NVARCHAR(MAX),
AMT_APPLICATION NVARCHAR(MAX),
AMT_CREDIT NVARCHAR(MAX),
CODE_REJECT_REASON NVARCHAR(MAX)
);
GO

IF OBJECT_ID('silver.bureau', 'U') IS NOT NULL
	DROP TABLE silver.bureau;
GO
CREATE TABLE silver.bureau(
SK_ID_CURR NVARCHAR(MAX),
SK_ID_BUREAU NVARCHAR(MAX),
CREDIT_ACTIVE NVARCHAR(MAX),
CREDIT_CURRENCY NVARCHAR(MAX),
AMT_CREDIT_SUM_OVERDUE NVARCHAR(MAX),
CREDIT_TYPE NVARCHAR(MAX)
);
GO
IF OBJECT_ID('silver.credit_card_balance', 'U') IS NOT NULL
	DROP TABLE silver.credit_card_balance;
GO
CREATE TABLE silver.credit_card_balance(
SK_ID_PREV NVARCHAR(MAX),
SK_ID_CURR NVARCHAR(MAX),
MONTHS_BALANCE NVARCHAR(MAX),
AMT_BALANCE NVARCHAR(MAX),
AMT_CREDIT_LIMIT_ACTUAL NVARCHAR(MAX),
AMT_PAYMENT_TOTAL_CURRENT NVARCHAR(MAX),
CNT_DRAWINGS_ATM_CURRENT NVARCHAR(MAX)
);
 GO
IF OBJECT_ID('silver.installments_payments', 'U') IS NOT NULL
	DROP TABLE silver.installments_payments;
GO
CREATE TABLE silver.installments_payments(
SK_ID_PREV NVARCHAR(MAX),
SK_ID_CURR NVARCHAR(MAX),
DAYS_INSTALMENT	NVARCHAR(MAX),
DAYS_ENTRY_PAYMENT NVARCHAR(MAX)
);
GO
IF OBJECT_ID('silver.POS_CASH_balance','U') IS NOT NULL
	DROP TABLE silver.POS_CASH_balance;
GO
CREATE TABLE silver.POS_CASH_balance(
SK_ID_PREV NVARCHAR(MAX),
SK_ID_CURR NVARCHAR(MAX),
CNT_INSTALMENT_FUTURE NVARCHAR(MAX),
SK_DPD_DEF NVARCHAR(MAX)
);
GO
IF OBJECT_ID('silver.bureau_balance', 'U') IS NOT NULL
	DROP TABLE silver.bureau_balance;
GO
CREATE TABLE silver.bureau_balance(
SK_ID_BUREAU NVARCHAR(MAX),
MONTHS_BALANCE NVARCHAR(MAX),
STATUS NVARCHAR(MAX)
)
